### ISSUE TITLE
Creating a channel with an existing, half-completed pipe produces content message before offer

### ISSUE THREAD

**Issue by AArnott** [AArnott/Nerdbank.Streams#112]
Creating a duplex pipe and completing its input so that the other side cannot transmit but may receive causes the channel based on it to send content before the offer, leading to the reverse side throwing an exception.

```cs
[Fact]
public async Task OfferReadOnlyPipe()
{
    // Prepare a readonly pipe that is already fully populated with data for the other end to read.
    var pipePair = FullDuplexStream.CreatePipePair();
    pipePair.Item1.Input.Complete(); // we don't read -- we only write.
    await pipePair.Item1.Output.WriteAsync(new byte[] { 1, 2, 3 }, this.TimeoutToken);
    pipePair.Item1.Output.Complete();

    var ch1 = this.mx1.CreateChannel(new MultiplexingStream.ChannelOptions { ExistingPipe = pipePair.Item2 });
    await this.WaitForEphemeralChannelOfferToPropagateAsync();
    var ch2 = this.mx2.AcceptChannel(ch1.Id);
    var readResult = await ch2.Input.ReadAsync(this.TimeoutToken);
    Assert.Equal(3, readResult.Buffer.Length);
    ch2.Input.AdvanceTo(readResult.Buffer.End);
    readResult = await ch2.Input.ReadAsync(this.TimeoutToken);
    Assert.True(readResult.IsCompleted);
}
```

The trace output from this test is:

```
00:00:00.0000515 mx2 Information: 1 : Multiplexing protocol established successfully.
00:00:00.0000833 mx2 Verbose: 18 : Waiting for next frame
00:00:00.0001529 mx1 Information: 1 : Multiplexing protocol established successfully.
00:00:00.0001939 mx1 Verbose: 18 : Waiting for next frame
00:00:00.0069823 mx1 channel 2 Verbose: 0 : 0 of 0 bytes will be transmitted.
00:00:00.0070127 mx1 channel 2 Verbose: 0 : Transmission terminated because the writer completed.
00:00:00.0070442 mx1 channel 2 Information: 5 : Channel self-closing because both parties have completed transmission.
00:00:00.0000432 mx1 channel 1 Verbose: 0 : 3 of 3 bytes will be transmitted.
00:00:00.0011600 mx1 Information: 13 : Sending Content frame for channel 1, carrying 3 bytes of content.
0x010203
00:00:00.0001543 mx1 channel 1 Verbose: 0 : Transmission terminated because the writer completed.
00:00:00.0012648 mx1 Information: 13 : Sending Offer frame for channel 1, carrying 0 bytes of content.
00:00:00.0013175 mx1 Information: 13 : Sending Offer frame for channel 3, carrying 22 bytes of content.
0x457068656D6572616C4368616E6E656C576169746572
00:00:00.0013772 mx2 Information: 7 : Waiting to accept channel "EphemeralChannelWaiter", when offered by the other side.
00:00:00.0015335 mx2 Information: 14 : Received Content frame for channel 1 with 3 bytes of content.
00:00:00.0017257 mx2 Critical: 3 : Disposing self due to exception: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Nerdbank.Streams.MultiplexingStream.<OnContentAsync>d__58.MoveNext() in D:\git\Nerdbank.Streams\src\Nerdbank.Streams\MultiplexingStream.cs:line 791
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter.GetResult()
   at Nerdbank.Streams.MultiplexingStream.<ReadStreamAsync>d__55.MoveNext() in D:\git\Nerdbank.Streams\src\Nerdbank.Streams\MultiplexingStream.cs:line 698
00:00:00.0017666 mx2 Information: 6 : Disposing.
00:00:00.0018367 mx1 Information: 6 : Disposing.
00:00:00.0006437 mx1 channel 3 Verbose: 0 : 0 of 0 bytes will be transmitted.
00:00:00.0006772 mx1 channel 3 Verbose: 0 : Transmission terminated because the writer completed.
00:00:00.0007077 mx1 channel 3 Information: 5 : Channel self-closing because both parties have completed transmission.
00:00:00.0010616 mx1 channel 1 Information: 5 : Channel self-closing because both parties have completed transmission.
00:00:00.0022073 mx1 Information: 6 : Disposing.
00:00:00.0022351 mx2 Information: 6 : Disposing.
```

**Comment by AArnott** [comment]
It doesn't even have to be half-completed. It just has to have data in it before the offer is made (by using the `ExistingPipe` option).
