### ISSUE TITLE
Sequence<T>.Reset sometimes throws ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by AArnott** [AArnott/Nerdbank.Streams#182]
After calling `Sequence<T>.AdvanceTo`, the `Sequence<T>.Reset()` method *may* throw `ArgumentOutOfRangeException`.

**Repro**

```cs
        var seq = new Sequence<object>(new MockMemoryPool<object> { Contents = { new object[4] } });
        seq.Write(new object[3]);
        seq.AdvanceTo(seq.AsReadOnlySequence.GetPosition(2));
        seq.Reset();
```

```
   at System.Span`1.Slice(Int32 start, Int32 length)
   at Nerdbank.Streams.Sequence`1.SequenceSegment.ClearReferences(Int32 startIndex, Int32 length) in D:\git\Nerdbank.Streams\src\Nerdbank.Streams\Sequence`1.cs:line 459
   at Nerdbank.Streams.Sequence`1.SequenceSegment.ResetMemory(ArrayPool`1 arrayPool) in D:\git\Nerdbank.Streams\src\Nerdbank.Streams\Sequence`1.cs:line 399
   at Nerdbank.Streams.Sequence`1.RecycleAndGetNext(SequenceSegment segment) in D:\git\Nerdbank.Streams\src\Nerdbank.Streams\Sequence`1.cs:line 301
   at Nerdbank.Streams.Sequence`1.Reset() in D:\git\Nerdbank.Streams\src\Nerdbank.Streams\Sequence`1.cs:line 215
   at SequenceTests.Reset_AfterPartialAdvance() in D:\git\Nerdbank.Streams\src\Nerdbank.Streams.Tests\SequenceTests.cs:line 84
Result Message:	
System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values.
Parameter name: start
```

The critical point to the repro is that the number of elements discarded with `AdvanceTo` must exceed the slack in the backing array.

**Comment by AArnott** [comment]
This bug was introduced in caee1d18 and first released in v2.1.
