### ISSUE TITLE
MultiplexingChannel may send ChannelTerminated followed by ChannelAccepted

### ISSUE THREAD

**Issue by AArnott** [AArnott/Nerdbank.Streams#209]
The `CancelChannelOfferBeforeAcceptance` test [failed recently](https://dev.azure.com/andrewarnott/OSS/_build/results?buildId=3144&view=ms.vss-test-web.build-test-results-tab&runId=1018388&resultId=100625&paneView=attachments) with evidence in the trace that the accepting party sent a `ChannelTerminated` message for channel 2 followed by a `OfferAccepted` message for that same channel. Clearly that order of messages should never be transmitted.

```
00:00:00.0004273 mx1 Information: 20 : Multiplexing protocol handshake beginning with major version 2.
00:00:00.0007864 mx2 Information: 20 : Multiplexing protocol handshake beginning with major version 2.
00:00:00.0013376 mx2 Information: 1 : Multiplexing protocol established successfully.
00:00:00.0016810 mx2 Verbose: 18 : Waiting for next frame
00:00:00.0051430 mx1 Information: 1 : Multiplexing protocol established successfully.
00:00:00.0054815 mx1 Verbose: 18 : Waiting for next frame
00:00:00.0060032 mx1 Information: 13 : Sending Offer frame for channel 2, carrying 7 bytes of content.
0x92A0CE00019000
00:00:00.0066392 mx1 Information: 12 : Offer of channel 2 ("") canceled.
00:00:00.0082617 mx2 Information: 14 : Received Offer frame for channel 2 with 7 bytes of content.
00:00:00.0086320 mx2 Information: 10 : Remote party offers channel 2 "" which has no pending AcceptChannelAsync
00:00:00.0095992 mx2 Verbose: 18 : Waiting for next frame
00:00:00.0100994 mx1 Information: 13 : Sending ContentWritingCompleted frame for channel 2, carrying 0 bytes of content.
00:00:00.0107333 mx1 Information: 11 : Local channel 2 "" stream disposed.
00:00:00.0111118 mx1 Information: 13 : Sending ChannelTerminated frame for channel 2, carrying 0 bytes of content.
00:00:00.0115362 mx2 Information: 14 : Received ContentWritingCompleted frame for channel 2 with 0 bytes of content.
00:00:00.0122729 mx2 Information: 8 : Accepting channel 2 "" which is already offered by the other side.
00:00:00.0126541 mx2 Verbose: 18 : Waiting for next frame
00:00:00.0130488 mx2 Information: 14 : Received ChannelTerminated frame for channel 2 with 0 bytes of content.
00:00:00.0138132 mx2 Information: 11 : Local channel 2 "" stream disposed.
00:00:00.0142395 mx2 Information: 13 : Sending ChannelTerminated frame for channel 2, carrying 0 bytes of content.
00:00:00.0145272 mx2 Verbose: 18 : Waiting for next frame
00:00:00.0149317 mx1 Information: 14 : Received ChannelTerminated frame for channel 2 with 0 bytes of content.
00:00:00.0152815 mx1 Verbose: 18 : Waiting for next frame
00:00:00.0156903 mx2 Information: 13 : Sending OfferAccepted frame for channel 2, carrying 6 bytes of content.
0x91CE00019000
00:00:00.0171032 mx2 Information: 7 : Waiting to accept channel "", when offered by the other side.
00:00:00.0175526 mx1 Information: 14 : Received OfferAccepted frame for channel 2 with 6 bytes of content.
00:00:00.0184367 mx1 Critical: 3 : Disposing self due to exception: Nerdbank.Streams.MultiplexingProtocolException: Offer accepted for unknown or forgotten channel ID 2
   at Nerdbank.Streams.MultiplexingStream.OnOfferAccepted(FrameHeader header, ReadOnlySequence`1 payloadBuffer) in D:\a\1\s\src\Nerdbank.Streams\MultiplexingStream.cs:line 791
   at Nerdbank.Streams.MultiplexingStream.<ReadStreamAsync>d__55.MoveNext() in D:\a\1\s\src\Nerdbank.Streams\MultiplexingStream.cs:line 673
00:00:00.0188158 mx1 Information: 6 : Disposing.
00:00:00.0191882 mx2 Information: 6 : Disposing.
Verified the channel offer was canceled before acceptance condition.
00:00:00.0217640 mx1 Information: 6 : Disposing.
00:00:00.0221121 mx2 Information: 6 : Disposing.
```

**Comment by AArnott** [comment]
I can still reproduce this on `main` in the debugger by controlling thread execution order.
