### ISSUE TITLE
`SendFrameAsync` still running after writer is terminated

### ISSUE THREAD

**Issue by AArnott** [AArnott/Nerdbank.Streams#255]
```
InProcRemoteClient Critical: 3 : Disposing self due to exception: System.InvalidOperationException: Writing is not allowed after writer was completed.
   at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_NoWritingAllowed()
   at System.IO.Pipelines.Pipe.GetMemory(Int32 sizeHint)
   at MessagePack.Utilities.GetMemoryCheckResult[T](IBufferWriter`1 bufferWriter, Int32 size)
   at MessagePack.BufferWriter..ctor(IBufferWriter`1 output)
   at MessagePack.MessagePackWriter..ctor(IBufferWriter`1 writer)
   at Nerdbank.Streams.MultiplexingStream.V3Formatter.WriteFrame(FrameHeader header, ReadOnlySequence`1 payload)
   at Nerdbank.Streams.MultiplexingStream.&lt;SendFrameAsync&gt;d__71.MoveNext()
InProcRemoteClient Information: 6 : Disposing.
```

**Comment by xamele0n** [comment]
Any assumptions here?

**Comment by AArnott** [comment]
I don't understand your question, @xamele0n.
