### ISSUE TITLE
ArgumentException thrown from Sequence<T>.AdvanceTo

### ISSUE THREAD

**Issue by AArnott** [AArnott/Nerdbank.Streams#44]
From [this build](https://andrewarnott.visualstudio.com/OSS/_build/results?buildId=310&view=logs), which consumed Nerdbank.Streams v2.0.165-beta, failed here:

https://github.com/AArnott/vs-streamjsonrpc/blob/80ff0009ff93116773c8279e7e3c8414a1f3927f/src/StreamJsonRpc/HeaderDelimitedMessageHandler.cs#L207

Failure log follows:

```
2018-09-28T21:21:57.3498266Z [xUnit.net 00:00:12.7193559]         Server Critical: 13 : Connection closing (StreamError: Reading JSON RPC from the stream failed with ArgumentException: Position does not represent a valid position in this sequence.
2018-09-28T21:21:57.3498551Z [xUnit.net 00:00:12.7193830]         Parameter name: position). System.ArgumentException: Position does not represent a valid position in this sequence.
2018-09-28T21:21:57.3498612Z [xUnit.net 00:00:12.7194027]         Parameter name: position
2018-09-28T21:21:57.3498705Z [xUnit.net 00:00:12.7194191]            at Nerdbank.Streams.Sequence`1.AdvanceTo(SequencePosition position)
2018-09-28T21:21:57.3498771Z [xUnit.net 00:00:12.7194353]            at Nerdbank.Streams.StreamPipeReader.AdvanceTo(SequencePosition consumed, SequencePosition examined)
2018-09-28T21:21:57.3498880Z [xUnit.net 00:00:12.7194498]            at Nerdbank.Streams.StreamPipeReader.AdvanceTo(SequencePosition consumed)
2018-09-28T21:21:57.3498952Z [xUnit.net 00:00:12.7194658]            at StreamJsonRpc.HeaderDelimitedMessageHandler.<ReadCoreAsync>d__25.MoveNext() in /__w/1/s/src/StreamJsonRpc/HeaderDelimitedMessageHandler.cs:line 207
2018-09-28T21:21:57.3499242Z [xUnit.net 00:00:12.7194890]         --- End of stack trace from previous location where exception was thrown ---
2018-09-28T21:21:57.3499349Z [xUnit.net 00:00:12.7195030]            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2018-09-28T21:21:57.3499415Z [xUnit.net 00:00:12.7195190]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-09-28T21:21:57.3499526Z [xUnit.net 00:00:12.7195332]            at StreamJsonRpc.MessageHandlerBase.<ReadAsync>d__14.MoveNext() in /__w/1/s/src/StreamJsonRpc/MessageHandlerBase.cs:line 93
2018-09-28T21:21:57.3499879Z [xUnit.net 00:00:12.7195493]         --- End of stack trace from previous location where exception was thrown ---
2018-09-28T21:21:57.3499944Z [xUnit.net 00:00:12.7195653]            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2018-09-28T21:21:57.3500050Z [xUnit.net 00:00:12.7195792]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-09-28T21:21:57.3500118Z [xUnit.net 00:00:12.7195952]            at StreamJsonRpc.JsonRpc.<ReadAndHandleRequestsAsync>d__93.MoveNext() in /__w/1/s/src/StreamJsonRpc/JsonRpc.cs:line 1519
2018-09-28T21:21:57.3500237Z [xUnit.net 00:00:12.7196095]         Server Critical: 13 : Connection closing (StreamError: Reading JSON RPC from the stream failed with BadRpcHeaderException: Header does not end with expected 
2018-09-28T21:21:57.3500643Z [xUnit.net 00:00:12.7196337]          character sequence.). StreamJsonRpc.BadRpcHeaderException: Header does not end with expected 
2018-09-28T21:21:57.3500888Z [xUnit.net 00:00:12.7196507]          character sequence.
2018-09-28T21:21:57.3500955Z [xUnit.net 00:00:12.7196647]            at StreamJsonRpc.HeaderDelimitedMessageHandler.<ReadHeadersAsync>d__35.MoveNext() in /__w/1/s/src/StreamJsonRpc/HeaderDelimitedMessageHandler.cs:line 441
2018-09-28T21:21:57.3501459Z [xUnit.net 00:00:12.7196882]         --- End of stack trace from previous location where exception was thrown ---
2018-09-28T21:21:57.3501765Z [xUnit.net 00:00:12.7197042]            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2018-09-28T21:21:57.3501955Z [xUnit.net 00:00:12.7197182]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-09-28T21:21:57.3502661Z [xUnit.net 00:00:12.7197345]            at StreamJsonRpc.HeaderDelimitedMessageHandler.<ReadCoreAsync>d__25.MoveNext() in /__w/1/s/src/StreamJsonRpc/HeaderDelimitedMessageHandler.cs:line 171
2018-09-28T21:21:57.3503131Z [xUnit.net 00:00:12.7197560]         --- End of stack trace from previous location where exception was thrown ---
2018-09-28T21:21:57.3503317Z [xUnit.net 00:00:12.7197720]            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2018-09-28T21:21:57.3503414Z [xUnit.net 00:00:12.7197880]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-09-28T21:21:57.3503565Z [xUnit.net 00:00:12.7198023]            at StreamJsonRpc.MessageHandlerBase.<ReadAsync>d__14.MoveNext() in /__w/1/s/src/StreamJsonRpc/MessageHandlerBase.cs:line 93
2018-09-28T21:21:57.3503966Z [xUnit.net 00:00:12.7198185]         --- End of stack trace from previous location where exception was thrown ---
2018-09-28T21:21:57.3504095Z [xUnit.net 00:00:12.7198327]            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2018-09-28T21:21:57.3504223Z [xUnit.net 00:00:12.7198485]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-09-28T21:21:57.3504336Z [xUnit.net 00:00:12.7198647]            at StreamJsonRpc.JsonRpc.<ReadAndHandleRequestsAsync>d__93.MoveNext() in /__w/1/s/src/StreamJsonRpc/JsonRpc.cs:line 1519
```

**Comment by AArnott** [comment]
No repro since then. And it may be a bug in the caller.
