### ISSUE TITLE
BufferTextWriter bugs

### ISSUE THREAD

**Issue by AArnott** [AArnott/Nerdbank.Streams#91]
https://github.com/microsoft/vs-streamjsonrpc/issues/303 calls out a few exceptions that seem to be thrown erratically as if there's a race condition, or perhaps specific writing patterns that cause the `BufferTextWriter` to fail.

**Comment by joshlang** [comment]
It would be difficult to extra a minimal repo, unfortunately.

Here's another stack traces:

```
Error writing JSON RPC Result: InvalidOperationException: Stack empty.//StreamError/System.InvalidOperationException: Stack empty.
   at System.Collections.Generic.Stack`1.ThrowForEmptyStack()
   at System.Collections.Generic.Stack`1.Pop()
   at Nerdbank.Streams.Sequence`1.GetSegment(Int32 sizeHint)
   at Nerdbank.Streams.Sequence`1.GetMemory(Int32 sizeHint)
   at Nerdbank.Streams.BufferTextWriter.EncodeCharacters(Boolean flushEncoder)
   at Nerdbank.Streams.BufferTextWriter.Write(ReadOnlySpan`1 buffer)
   at Nerdbank.Streams.BufferTextWriter.Write(String value)
   at Newtonsoft.Json.Utilities.JavaScriptUtils.WriteEscapedJavaScriptString(TextWriter writer, String s, Char delimiter, Boolean appendDelimiters, Boolean[] charEscapeFlags, StringEscapeHandling stringEscapeHandling, IArrayPool`1 bufferPool, Char[]& writeBuffer)
   at Newtonsoft.Json.JsonTextWriter.WriteEscapedString(String value, Boolean quote)
   at Newtonsoft.Json.JsonTextWriter.WriteValue(String value)
   at Newtonsoft.Json.Linq.JValue.WriteTo(JsonWriter writer, JsonConverter[] converters)
   at Newtonsoft.Json.Linq.JProperty.WriteTo(JsonWriter writer, JsonConverter[] converters)
   at Newtonsoft.Json.Linq.JObject.WriteTo(JsonWriter writer, JsonConverter[] converters)
   at Newtonsoft.Json.Linq.JArray.WriteTo(JsonWriter writer, JsonConverter[] converters)
   at Newtonsoft.Json.Linq.JProperty.WriteTo(JsonWriter writer, JsonConverter[] converters)
   at Newtonsoft.Json.Linq.JObject.WriteTo(JsonWriter writer, JsonConverter[] converters)
   at Newtonsoft.Json.Linq.JProperty.WriteTo(JsonWriter writer, JsonConverter[] converters)
   at Newtonsoft.Json.Linq.JObject.WriteTo(JsonWriter writer, JsonConverter[] converters)
   at Newtonsoft.Json.Linq.JProperty.WriteTo(JsonWriter writer, JsonConverter[] converters)
   at Newtonsoft.Json.Linq.JObject.WriteTo(JsonWriter writer, JsonConverter[] converters)
   at StreamJsonRpc.JsonMessageFormatter.WriteJToken(IBufferWriter`1 contentBuffer, JToken json)
   at StreamJsonRpc.JsonMessageFormatter.Serialize(IBufferWriter`1 contentBuffer, JsonRpcMessage message)
   at StreamJsonRpc.WebSocketMessageHandler.WriteCoreAsync(JsonRpcMessage content, CancellationToken cancellationToken)
   at StreamJsonRpc.MessageHandlerBase.WriteAsync(JsonRpcMessage content, CancellationToken cancellationToken)
   at StreamJsonRpc.JsonRpc.HandleRpcAsync(JsonRpcMessage rpc)
```

Again, after happening, we're stuck in this connect/disconnect loop:

```
Error writing JSON RPC Result: InvalidOperationException: This instance must be flushed before being reinitialized.//StreamError/System.InvalidOperationException: This instance must be flushed before being reinitialized.
   at Microsoft.Verify.Operation(Boolean condition, String message)
   at Nerdbank.Streams.BufferTextWriter.Initialize(IBufferWriter`1 bufferWriter, Encoding encoding)
   at StreamJsonRpc.JsonMessageFormatter.WriteJToken(IBufferWriter`1 contentBuffer, JToken json)
   at StreamJsonRpc.JsonMessageFormatter.Serialize(IBufferWriter`1 contentBuffer, JsonRpcMessage message)
   at StreamJsonRpc.WebSocketMessageHandler.WriteCoreAsync(JsonRpcMessage content, CancellationToken cancellationToken)
   at StreamJsonRpc.MessageHandlerBase.WriteAsync(JsonRpcMessage content, CancellationToken cancellationToken)
   at StreamJsonRpc.JsonRpc.HandleRpcAsync(JsonRpcMessage rpc)
```

**Comment by AArnott** [comment]
@joshlang  What version of Nerdbank.Streams.dll is running in this scenario? It seems that the particular exception you're seeing with Stack.Pop above is impossible:

https://github.com/AArnott/Nerdbank.Streams/blob/3796430666841e72f133759ecc7d18ae7fd65066/src/Nerdbank.Streams/Sequence%601.cs#L235

So either you're using the same `BufferTextWriter` from multiple threads at once (which is not allowed) or you're using an older version of Nerdbank.Streams that might have a bug that we've already fixed.

**Comment by joshlang** [comment]
We are not using Nerdbank, nor BufferWriter, directly.

They come in through StreamJsonRpc 2.0.208, the latest on nuget, which brings in Nerdbank.Streams >= 2.2.26.

Here's the only code related to StreamJsonRpc, used in `public async Task HandleAsync(HttpContext context, Func<Task> next)` in a kestrel pipeline:
```
using var ws = await context.WebSockets.AcceptWebSocketAsync();
using var rpc = new JsonRpc(new WebSocketMessageHandler(ws, JsonMessageFormatter));
rpc.Disconnected += (s, e) => $"Disconnected: {e.Description}/{e.LastMessage}/{e.Reason}/{e.Exception}".Grr();
rpc.AddLocalRpcMethod(ProcessBlockMethodName, (Func<JObject, CancellationToken, Task<IBlock>>)ctx.HandleAsync);
rpc.StartListening();
await rpc.Completion;
```

The `.Grr()` is our debugging code :)

The stack traces etc from above come from the rpc.Disconnected event handler.

So, while it's possible that multiple threads are accessing BufferTextWriter, it would be happening from somewhere inside StreamJsonRpc I think.

**Comment by AArnott** [comment]
Great. I think I see the problem:

```cs
using var rpc = new JsonRpc(new WebSocketMessageHandler(ws, JsonMessageFormatter));
```

In this line, how is `JsonMessageFormatter`? If that's a shared instance that you're reusing, that's a problem. The message handler and formatter are only thread-safe for use within a single `JsonRpc` instance. Reusing the formatter across several `JsonRpc` instances is causing certain threading assumption it makes to be invalid. I'm frankly surprised this is only causing exceptions to be thrown once a day and not doing major data corruption too.

**Comment by joshlang** [comment]
We're still in dev-mode, so... yeah.  

Thanks for pointing that out!  We will make the fix immediately.

I did notice something else though in here: https://github.com/microsoft/vs-streamjsonrpc/blob/master/src/StreamJsonRpc/WebSocketMessageHandler.cs 

Only one call to SendAsync is allowed at any time, according to https://docs.microsoft.com/en-us/dotnet/api/system.net.websockets.websocket.sendasync?view=netframework-4.8

I could not spot any guard.  In JsonRpc.cs, you TransmitAsync responses, which seems appropriate, but could result in >1 WebSocket.SendAsync's being awaited at once.  It would not cause our problems, but just mentioning it because I came across it while searching for the problem (which you solved in the meantime hehe).  If you'd like me to open an issue over there, let me know.

**Comment by AArnott** [comment]
Awesome.

Regarding your SendAsync concern, if it is that you think `WebSocketMessageHandler` might call `SendAsync` more than once at a time, not to worry. Our base class takes care of that:

https://github.com/microsoft/vs-streamjsonrpc/blob/d0914a211921045b13e79a3a449e2c34a9d0786e/src/StreamJsonRpc/MessageHandlerBase.cs#L129

**Comment by joshlang** [comment]
Beautiful, thanks.

You're incredible responsive, eh :D  Thanks for all your help!

**Comment by AArnott** [comment]
You're quite welcome.
